### ISSUE TITLE
Revert to floor not round in index conversion

### ISSUE THREAD

**Issue by jasonmcewen** [astro-informatics/ssht#24]
See comment [here](https://github.com/astro-informatics/ssht/commit/235ad2b0dcf920475895d604e75c9b8707c08cfb#commitcomment-42229955).

This is to invert the index mapping: $i = \ell^2 + \ell + m$.

The inverse should be $\ell = floor(sqrt(i))$ and then $m = i - \ell^2 - \ell$.

So we need to use floor not round.

**Comment by mdavezac** [comment]
done
