### ISSUE TITLE
PyPI package missing some cmake files

### ISSUE THREAD

**Issue by auggiemarignier** [astro-informatics/ssht#29]
I've tried installing using `pip install pyssht` and it fails at the cmake stage - it can't find the `conan_dependencies` and `python-setup` files.  If you download the `.tar.gz` file from PyPI you'll see these files are missing
![Screenshot 2020-09-14 at 11 31 40](https://user-images.githubusercontent.com/42379892/93075685-0ea18500-f67e-11ea-8183-2207d9174e48.png)
![Screenshot 2020-09-14 at 11 33 56](https://user-images.githubusercontent.com/42379892/93075772-31339e00-f67e-11ea-9a0b-183ba03daa61.png)

**Comment by mdavezac** [comment]
Could you give it another go. It looks like it works on my mac and in an ubuntu container (after pip3 install --upgrade pip).

**Comment by auggiemarignier** [comment]
working now, cheers!
