### ISSUE TITLE
Ability to run inverse operations multithreaded

### ISSUE THREAD

**Issue by paddyroddy** [astro-informatics/ssht#44]
See this question https://stackoverflow.com/q/65044164/7359333 basically I'm able to run my tasks using `multiprocessing` but ideally would like to use a `multithreaded` solution.

The problem is related to `FFTW` www.fftw.org/fftw2_doc/fftw_3.html#SEC46. Is there a way we can force some calls to act single threaded?

**Comment by mreineck** [comment]
This should now work with version 1.4 and the `ducc0` backend. Just pass the desired number of threads using the `nthreads` parameter!

**Comment by jasonmcewen** [comment]
Thanks @mreineck (closing issue).

P.S. Have been a little busy last few days but will get back to your comments on other issues/PRs soon...
