### ISSUE TITLE
incorrect rotation direction in rotate image

### ISSUE THREAD

**Issue by mdavezac** [astro-informatics/ssht#45]
- rotate_flm should be consistent with rotate_image: add test
- this [line](https://github.com/astro-informatics/ssht/blob/6493a2f4d92f021f5a1d3bfacc3fc28d7ecd87ae/src/pyssht/pyssht.pyx#L1094) ought to rotate by -gamma, -beta, -alpha

**Comment by jasonmcewen** [comment]
@mdavezac On a quick look this change does not look correct.  We should be changing the rotation (alpha,beta,gamma) to (-gamma,-beta,-alpha) but it simply looks like the sign of the cartesian coordinates have been changed?

Did you check the change makes `rotate_image` consistent with `rotate_flm` (as dicussed in the comment above)?
